export const categoryData = [
    {
        id: "CAT-1001",
        name: "Electronics",
        description: "Electronic devices and accessories",
        icon: "📱",
        productCount: 156,
        subcategories: ["Smartphones", "Laptops", "Tablets", "Accessories"],
        lastUpdated: "Apr 10, 2024",
    },
    {
        id: "CAT-1002",
        name: "Clothing",
        description: "Apparel and fashion items",
        icon: "👕",
        productCount: 243,
        subcategories: [
            "Men's Wear",
            "Women's Wear",
            "Kids",
            "Accessories",
        ],
        lastUpdated: "Apr 12, 2024",
    },
    {
        id: "CAT-1003",
        name: "Home & Kitchen",
        description: "Furniture, appliances, and home decor",
        icon: "🏠",
        productCount: 189,
        subcategories: [
            "Furniture",
            "Kitchen Appliances",
            "Home Decor",
            "Bedding",
        ],
        lastUpdated: "Apr 8, 2024",
    },
    {
        id: "CAT-1004",
        name: "Books",
        description: "Books, ebooks, and audiobooks",
        icon: "📚",
        productCount: 112,
        subcategories: [
            "Fiction",
            "Non-fiction",
            "Educational",
            "Magazines",
        ],
        lastUpdated: "Apr 5, 2024",
    },
    {
        id: "CAT-1005",
        name: "Sports & Outdoors",
        description: "Sporting goods and outdoor equipment",
        icon: "⚽",
        productCount: 98,
        subcategories: [
            "Exercise Equipment",
            "Team Sports",
            "Outdoor Recreation",
            "Camping",
        ],
        lastUpdated: "Apr 15, 2024",
    },
    {
        id: "CAT-1006",
        name: "Beauty & Personal Care",
        description: "Cosmetics, skincare, and personal grooming products",
        icon: "💄",
        productCount: 176,
        subcategories: ["Skincare", "Makeup", "Hair Care", "Fragrances"],
        lastUpdated: "Apr 3, 2024",
    },
    {
        id: "CAT-1007",
        name: "Toys & Games",
        description: "Toys, games, and entertainment items for kids",
        icon: "🧸",
        productCount: 84,
        subcategories: [
            "Action Figures",
            "Board Games",
            "Educational Toys",
            "Puzzles",
        ],
        lastUpdated: "Apr 7, 2024",
    },
    {
        id: "CAT-1008",
        name: "Automotive",
        description: "Car parts, accessories, and tools",
        icon: "🚗",
        productCount: 42,
        subcategories: ["Car Parts", "Accessories", "Tools", "Electronics"],
        lastUpdated: "Mar 25, 2024",
    },
]