export const productData = [
    {
        id: "PRD-1001",
        name: "Classic White T-Shirt",
        category: "Clothing",
        price: "$24.99",
        stock: 145,
        status: "Active",
        image: ["https://www.aeg.co.za/contentassets/da802fe7acdb4a039d509b11384f4049/how-to-use-gas-stove-safely-aeg-south-africa-thumb.jpg"],
        description: "High-quality cotton t-shirt...",
        sku: "CLO-TSHIRT-WHT-M",
        lastUpdated: "Jan 15, 2024",
        rating: 4.5,
        variations: ["White", "S", "M", "L", "XL"],
        tags: ["Essential", "Summer", "Basic"],
    },
    {
        id: "PRD-1002",
        name: "Blue Denim Jeans",
        category: "Clothing",
        price: "$59.99",
        stock: 78,
        status: "Active",
        image: ["https://maxima.com/img/JAvYiqudP9okS9NwicvYuaXcZVrHt-XGI-LhFtOJRgY/resize:fit:700:700/aHR0cHM6Ly9tYXhpbWEuY29tL21lZGlhL2NhdGFsb2cvcHJvZHVjdC83LzgvNzg2NW4xMTI5MDgxMC5qcGc_d2lkdGg9NzAwJmhlaWdodD03MDAmc3RvcmU9ZW4maW1hZ2UtdHlwZT1pbWFnZQ.jpg?type=catalog"],
        description: "Classic blue denim jeans...",
        sku: "CLO-JEANS-BLU-32",
        lastUpdated: "Feb 2, 2024",
        rating: 4.7,
        variations: ["Blue", "30", "32", "34", "36"],
        tags: ["Essential", "Casual", "Denim"],
    },
    {
        id: "PRD-1003",
        name: "Leather Wallet",
        category: "Accessories",
        price: "$34.99",
        stock: 52,
        status: "Active",
        image: ["https://tummachines.com/wp-content/uploads/2023/11/bomber-beige-1.jpg"],
        description: "Genuine leather wallet...",
        sku: "ACC-WALLET-BRN",
        lastUpdated: "Feb 10, 2024",
        rating: 4.3,
        variations: ["Brown", "Black"],
        tags: ["Accessories", "Gift"],
    },
    {
        id: "PRD-1004",
        name: "Wireless Headphones",
        category: "Electronics",
        price: "$129.99",
        stock: 23,
        status: "Low Stock",
        image: ["https://bizweb.dktcdn.net/100/369/010/products/89.jpg?v=1720493174280"],
        description: "Noise-cancelling wireless headphones...",
        sku: "ELEC-HEAD-BLK",
        lastUpdated: "Mar 5, 2024",
        rating: 4.8,
        variations: ["Black", "White", "Blue"],
        tags: ["Electronics", "Audio"],
    },
    {
        id: "PRD-1005",
        name: "Running Shoes",
        category: "Footwear",
        price: "$89.99",
        stock: 67,
        status: "Active",
        image: ["https://images-cdn.ubuy.co.in/65a92b391ffd8a68a7381298-crysully-men-39-s-bomber-jacket-fall.jpg"],
        description: "Lightweight running shoes...",
        sku: "FTW-RUN-BLK-10",
        lastUpdated: "Mar 15, 2024",
        rating: 4.6,
        variations: ["Black", "8", "9", "10", "11"],
        tags: ["Sports", "Running"],
    },
    {
        id: "PRD-1006",
        name: "Coffee Mug",
        category: "Home",
        price: "$14.99",
        stock: 112,
        status: "Active",
        image: ["https://product.hstatic.net/200000036106/product/zipup_collar_zip_leather_jacket_1_2438a19d9226446da1c7af33b4b41eef.jpg"],
        description: "Ceramic coffee mug...",
        sku: "HOM-MUG-WHT",
        lastUpdated: "Apr 1, 2024",
        rating: 4.2,
        variations: ["White", "Black", "Blue"],
        tags: ["Kitchen", "Gift"],
    },
]